---
title: "mlsquare"
---

**mlsquare** is an open source, deep tech initiative to democratize ML. The fundamental tenet is, use ML to make ML useful. 

## Past ML software projects

*   [mlsquare](https://github.com/mlsquare/mlsquare): make ML interoperable [paper](https://dl.acm.org/doi/10.1145/3486001.3486243)

## WIP ML software projects
* [FedEm](https://github.com/mlsquare/fedem): a framework to decentralize the development of LLMs

## Upcoming ML software projects

* *neural tokenizers* to enable the extension of English-centric LLMs to other languages

* *model grafting* via analytical and numerical approximations to enable efficient cross-architecture transfer learning

* *compute & data efficient training* via layer-by-layer and block-by-block LLM training, which is inherently embarrassingly parallel, and with potential analytical update rules (no need for backprop and gradients)

* *deep kernel machines* a framework for composing many transformer-like architectures with specifiable inductive biases

* *xKANs* a framework for composing many [KAN](https://arxiv.org/abs/2404.19756)-like architectures with specifiable non-parametric function approximators like cubic B-splines, Chebyshev polynomials, Wavelets, etc..

* *embeddings for tabular data* bridge the gap between tabular and modern deep learning models, and bring deep learning architectures perform no worse than tree-based models like the battle tested catboost


## Upcoming Courses

* *MLOps: Theory and Practice* for upper level undergraduate students

* *Theory of Deep Learning: Why it works - A Constructionist Approach* for upper level undergraduate students 

* *Ilya Sutskever's: [30 papers](https://arc.net/folder/D0472A20-9C20-4D3F-B145-D2865C0A9FEE?trk=public_post_comment-text)* - Walk through


Yours openly \
The Saddle Point \

Follow on [X/Twitter](https://x.com/TheSaddlePoint) \
Follow on [LinkedIn](https://linkedin.com/in/somasdhavala) \
Join the Discord server [here](https://discord.gg/TbW3kueqKR)